### ISSUE TITLE
Ejercicio 1 (Issue General)

### ISSUE THREAD

**Issue by royeden** [Maxi-F/TP_integrador#1]
# Ver consigna en el README.md
---

## Temas a resolver:
- Programar el algoritmo de Dijkstra.
- Programar la fórmula requerida en la consigna.
- Hacer que sea realmente aleatorio el número en la fórmula.
- Testear.

---

*Esto va a ser dividido en issues menores así podemos asignar quién hace cada cosa.*

### Recuerden trabajar esto siempre en el branch correspondiente ([Ejercicio 1](https://github.com/Maxi-F/TP_integrador/tree/ejercicio-1)).

**Comment by Maxi-F** [comment]
Acabo de ver en el foro que andan preguntando por este ejercicio y que Natalia Perez Lopez (Quien corrige los trabajos) recomienda el algoritmo de Dijkstra, pero todos preguntan si esta bien, ya que el algoritmo solo devuelve el "Camino más corto", no uno que pase obligatoriamente por todos los nodos (colegios en este caso).

Natalia todavía no respondió.
