### ISSUE TITLE
Programar métodos para recorrer el grafo (Ejercicio 1)

### ISSUE THREAD

**Issue by royeden** [Maxi-F/TP_integrador#10]
Es necesario tener métodos para recorrer el grafo, ya que estos nos van a servir para el algoritmo que utilicemos a la hora de encontrar el mejor camino. 

Refiere a los issues ( #5 y #9 ).

**Comment by AzulLuquet** [comment]
Se me había ocurrido que vaya tomando el camino más corto cada vez que tenga más de un camino por elegir. Mientras avanza, cuenta los nodos por los que pasó y controla que no pase dos veces por el mismo.
Cuando llega al último nodo, compara la cantidad total de nodos con la cantidad por los que pasó y si son distintos, vuelve al último nodo que tenía más de un camino como opción. Toma el camino más largo de ese nodo y sigue por los caminos más cortos.
Cuando llega al último, compara de vuelta y si aún no pasó por todos, va al anteúltimo nodo que tenía más de un camino como opción (porque con el último nodo ya intentó).
Repite lo mismo, cada vez yendo un nodo más atrás hasta encontrar un camino que pase por todos los nodos.
Esto no asegura que sea el camino más corto, debería guardar el peso de ese camino y volver a repetir el proceso buscando otro camino distinto que pueda llegar a ser más corto.
