### ISSUE TITLE
Reutilizar código del TP de Pablo (Ejercicio 2)

### ISSUE THREAD

**Issue by Maxi-F** [Maxi-F/TP_integrador#6]
# Reutilizar:

---

## Tenemos que agregar/cambiar en el código del TP de Pablo:
- Estructuras dinámicas
- Patrones de búsqueda y ordenamiento (Para las estructuras dinámicas)
- Cambiar nombres de las variables/subprogramas para que coincidan con el enunciado *(Esto se puede ver mas adelante, cuando ya esté el enunciado redactado)*. 

---

### Recuerden trabajar esto siempre en el branch correspondiente ([Ejercicio 2](https://github.com/Maxi-F/TP_integrador/tree/ejercicio-2)).

**Comment by karengrams** [comment]
Queriamos utilizar que el usuario coloque el tamaño del vector para este punto, sin embargo, no sabemos si estamos en lo correcto en cuanto a la idea que queremos aplicar, que es la siguiente: el usuario colocara la cantidad de candidatos que fueron recibidos para no desperdiciar memoria.
Necesitamos su ok, aunque vamos a avanzar con ello asi no nos atrasamos.
Besitos Karen.

**Comment by Maxi-F** [comment]
Y si en vez de pedirle al usuario la cantidad de votos, se hace una lista con los candidatos recibidos? Es mas dificil pero a la vez mas optimo porque no le va a estar pidiendo al usuario que ingrese los candidatos recibidos por cada telegrama, y no se usa memoria de más.

**Comment by karengrams** [comment]
Estaba pensando en que coloque los partidos que desea ingresar y después le tira los posibles partidos (que siguen siendo 29) y después le pida la cantidad de votos. 
Puede que esté mal pero es lo que se me acaba de ocurrir.

**Comment by Maxi-F** [comment]
Pero la cantidad de votos (de los telegramas) viene ya puesta dentro de los archivos, lo único que el programa tendría que hacer es leer la cantidad de votos Y a quién le corresponde (candidato) para subirlos al archivo de procesados.

Recién me estoy dando cuenta que faltaría un issue para hardcodear todos los archivos. ahora lo creo.

**Comment by karengrams** [comment]
Bellacos,
Tengo un problema. No se si saben, pero estoy haciendo el menu del codigo que corresponde al tema, y a la hora de agregar un nuevo candidato a la mesa (hicimos listas con sublistas), no me estaria saliendo la parte de que, si esa sublista ya tiene el candidato ingresado con el nombre, es decir, yo tengo una sublista de candidatos en la cual ya esta Mauricio Macri, no pueda ingresarlo dos veces en esa mesa. No se si se me logra entender, si alguien me tira un indicio de como sorongo lo puedo solcionar, se lo super agradeceria.
Besos, Karen (ahre).
