### ISSUE TITLE
Redactar/editar un enunciado (Ejercicio 2)

### ISSUE THREAD

**Issue by royeden** [Maxi-F/TP_integrador#7]
# Redactar:

Debido a que vamos a reutilizar código de un ejercicio ya resuelto (que posee una estructura similar), tenemos que redactar el ejercicio (ya sea adaptando la consigna original o reescribiendola desde cero).

## Recuerden trabajar esto siempre en el branch correspondiente ([Ejercicio 2](https://github.com/Maxi-F/TP_integrador/tree/ejercicio-2)).

**Comment by Maxi-F** [comment]
Ahi subi en la carpeta de ejercicio-2 un archivo que se llama "enunciado.txt". Tambien escribí una especie de enunciado a ver que les parece!
